# Generated by Django 3.2.25 on 2025-02-19 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20250217_2116"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
    ]
